name: My First Workflow

on:push

job:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Welcome message
      run:echo "My first Git Hub Actions Job"

      - name: List filters
      run: ls

      - name: read file
      run: cat readme.md